IF NOT EXISTS (SELECT * FROM master.dbo.sysdatabases WHERE [name] = 'SANNET')
BEGIN
	PRINT 'Creating "SANNET" database"..'

	CREATE DATABASE [SANNET]
		CONTAINMENT = NONE
		ON  PRIMARY 
	( NAME = N'SANNET', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.DEVSQL\MSSQL\DATA\SANNET.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
		LOG ON 
	( NAME = N'SANNET_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.DEVSQL\MSSQL\DATA\SANNET_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
	ALTER DATABASE [SANNET] SET COMPATIBILITY_LEVEL = 140

	IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
	begin
	EXEC [SANNET].[dbo].[sp_fulltext_database] @action = 'enable'
	end

	ALTER DATABASE [SANNET] SET ANSI_NULL_DEFAULT OFF 
	ALTER DATABASE [SANNET] SET ANSI_NULLS OFF 
	ALTER DATABASE [SANNET] SET ANSI_PADDING OFF 
	ALTER DATABASE [SANNET] SET ANSI_WARNINGS OFF 
	ALTER DATABASE [SANNET] SET ARITHABORT OFF 
	ALTER DATABASE [SANNET] SET AUTO_CLOSE OFF 
	ALTER DATABASE [SANNET] SET AUTO_SHRINK OFF 
	ALTER DATABASE [SANNET] SET AUTO_UPDATE_STATISTICS ON 
	ALTER DATABASE [SANNET] SET CURSOR_CLOSE_ON_COMMIT OFF 
	ALTER DATABASE [SANNET] SET CURSOR_DEFAULT  GLOBAL 
	ALTER DATABASE [SANNET] SET CONCAT_NULL_YIELDS_NULL OFF 
	ALTER DATABASE [SANNET] SET NUMERIC_ROUNDABORT OFF 
	ALTER DATABASE [SANNET] SET QUOTED_IDENTIFIER OFF 
	ALTER DATABASE [SANNET] SET RECURSIVE_TRIGGERS OFF 
	ALTER DATABASE [SANNET] SET  DISABLE_BROKER 
	ALTER DATABASE [SANNET] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
	ALTER DATABASE [SANNET] SET DATE_CORRELATION_OPTIMIZATION OFF 
	ALTER DATABASE [SANNET] SET TRUSTWORTHY OFF 
	ALTER DATABASE [SANNET] SET ALLOW_SNAPSHOT_ISOLATION OFF 
	ALTER DATABASE [SANNET] SET PARAMETERIZATION SIMPLE 
	ALTER DATABASE [SANNET] SET READ_COMMITTED_SNAPSHOT OFF 
	ALTER DATABASE [SANNET] SET HONOR_BROKER_PRIORITY OFF 
	ALTER DATABASE [SANNET] SET RECOVERY FULL 
	ALTER DATABASE [SANNET] SET  MULTI_USER 
	ALTER DATABASE [SANNET] SET PAGE_VERIFY CHECKSUM  
	ALTER DATABASE [SANNET] SET DB_CHAINING OFF 
	ALTER DATABASE [SANNET] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
	ALTER DATABASE [SANNET] SET TARGET_RECOVERY_TIME = 60 SECONDS 
	ALTER DATABASE [SANNET] SET DELAYED_DURABILITY = DISABLED 
	ALTER DATABASE [SANNET] SET QUERY_STORE = OFF
	ALTER DATABASE [SANNET] SET  READ_WRITE 
END
ELSE
	PRINT 'The database "SANNET" already exists..'