//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SANNET.DataModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NetworkConfiguration
    {
        public int Id { get; set; }
        public int NumHiddenLayers { get; set; }
        public int NumHiddenLayerNeurons { get; set; }
        public string InputNeuronDetails { get; set; }
        public string OutputNeuronDetails { get; set; }
    }
}
